admin/src/web/controllers/pagos.py
from calendar import month
from src.core.payment import costo_total
from flask import Blueprint, request
from flask import render_template, flash
from core import config
from src.core import payment
from src.core import associates
from flask import url_for
from flask import redirect
from src.web.helpers.permission import permisson_required
import datetime
from src.web.utils.exporters.pdf import generate_pdf_file_payment

payment_blueprint = Blueprint("payment", __name__, url_prefix="/payment")


@payment_blueprint.get("/")
@payment_blueprint.get("/<int:page_num>")
@permisson_required("payment_index")
def payment_index(page_num=1):
    """Returns the payment template"""

    search = request.args.get("search_field")
    paginated_users = associates.list_associate(
        page_num=page_num,
        per_page=config.get_per_page(),
        search=search,
        active=True,
        nroSocio=True,
    )
    return render_template("payment/index.html", users=paginated_users)


@payment_blueprint.route("/show/<id>")
@permisson_required("payment_show")
def show(id):
    """Shows the specific template for do a payment

    Args:
        id (int): Associated Identifier
    """
    associate = associates.get_associate(id)
    pending_payments = payment.pending_payments(id)
    # para cada pending_payments se debe calcular el costo total
    total = 0
    for pending_payment in pending_payments:
        print(pending_payment.state.value)
        if pending_payment.state.value == "Impago":
            mes = mesToInt(pending_payment.mes)
            costo_disciplines = associates.cost_disciplines(id, mes)
            costo_total = payment.costo_total(costo_disciplines, mes, pending_payment.AnioNum)
            total = total + costo_total
    disciplines = associates.getDisciplinas(id, datetime.datetime.now().month)
    return render_template(
        "payment/show.html",
        pending=pending_payments,
        user=associate,
        total=total,
        disciplines=disciplines,
    )


@payment_blueprint.route("/result/<id>/<id_pago>")
@permisson_required("payment_show")
def result(id, id_pago):
    """Given an user id and a payment, this function register a payment for the
        specified user, and validates that the payments are payed in order

    Args:
        id (int): User Identifier
        id_pago (int): Payment Identifier form the template

    """
    pending_payments = payment.payments_impagos(id)
    associate = associates.get_associate(id)
    pago = payment.get_payment(id_pago)
    mes = mesToInt(pago.mes)
    costo_disciplines = associates.cost_disciplines(id, mes)
    costo_total = payment.costo_total(costo_disciplines, mes, pago.AnioNum)
    todasDisciplinas = associates.getDisciplinas(id, mes)
    mesActual = datetime.datetime.now().month
    anioActual = datetime.datetime.now().year
    #chequear si el pago que se quiere pagar es del mes anterior o del mismo mes, sino no se puede pagar
    if (pago.mesNum > mesActual and pago.AnioNum >= anioActual):
            flash("Error! No se puede pagar una cuota siguiente al mes actual", "error")
            return redirect(url_for("payment.show", id=id))
    elif pago == pending_payments:
                return render_template(
                    "payment/report.html",
                    associate=associate,
                    costo_total=costo_total,
                    month=pago.mes.value,
                    id_pago=id_pago,
                    todasDisciplinas=todasDisciplinas,
                )
    else:
        flash("Error! Debe pagar las cuotas vencidas en orden", "error")
        return redirect(url_for("payment.show", id=id))


def mesToInt(mesPago):
    mes = str(mesPago)
    if mes == "Mes.E":
        return 1
    elif mes == "Mes.F":
        return 2
    elif mes == "Mes.M":
        return 3
    elif mes == "Mes.A":
        return 4
    elif mes == "Mes.May":
        return 5
    elif mes == "Mes.Jun":
        return 6
    elif mes == "Mes.Jul":
        return 7
    elif mes == "Mes.Ago":
        return 8
    elif mes == "Mes.S":
        return 9
    elif mes == "Mes.O":
        return 10
    elif mes == "Mes.N":
        return 11
    elif mes == "Mes.D":
        return 12


@payment_blueprint.route("/updatePayment/<id>/<id_pago>/<total>")
@permisson_required("payment_update")
def updatePayment(id, id_pago, total):
    payment.update_Payment(id_pago, total)
    flash("Pago realizado con éxito", "success")

    return redirect(url_for("payment.show", id=id))


@payment_blueprint.get("/emitir-certificado/")
def generate_voucher():
    """Generates a payment voucher given a Payment Model"""

    id = request.args.get("id")
    id_pago = request.args.get("id_pago")

    associado = associates.get_associate(id)
    pago = payment.get_payment(id_pago)
    texto = config.get_payment_voucher_description()
    nroComprobante = pago.nroComprobante

    return generate_pdf_file_payment(
        texto=texto,
        id=id_pago,
        associate=associado,
        month=pago.mes.value,
        costo_total=pago.total,
        fecha=pago.update_at,
        nroComprobante=nroComprobante,
    )

admin/src/web/templates/payment/certificado-pdf.html
<section class="sectionShow">
    <h1>Recibo #{{ nroComprobante }}</h1>
    <h1>Fecha: </strong>{{ fecha.strftime("%d/%m/%y") }}</h1>
    <h1>Recibimos de: {{associate.name}} {{associate.last_name}}</h1>
    <h1>El importe en pesos ${{costo_total}}</h1>
    <h1>Por el concepto de cuota societaria mes: {{month}}</h1>
    <p>{{ texto }}</p>
</section>

admin/src/web/templates/payment/comprobante.html
<section class="sectionShow">
    <h1>Asociado: {{associate.name}} {{associate.last_name}}</h1>
    <h2>Disciplinas :</h2>
    {% for d in todasDisciplinas %}
    <li>{{ d.name | capitalize }} </li>
    {% endfor %}

    <span class="labelShow"><strong>Mes: </strong>{{month}}</span>
    <span class="labelShow"><strong>Fecha: </strong>{{ datetime.now().strftime("%d/%m/%y") }}</span>
    <span class="labelShow"><strong>Total: </strong>{{costo_total}}</span>
</section>

admin/src/web/templates/payment/index.html
{% extends 'layout/layout.html' %}
{% block title %}Usuarios{% endblock %}
{%block content %}
{{ super() }}
<h1>Seccion de Pagos</h1>
<form class="filter_user" action="" method="GET">
    <input name="search_field" type="search" class="search-field" placeholder="Apellido o N° Socio..." {% if
        request.args.get('search_field') %} value="{{ request.args.get('search_field') }}" {% endif %} />
    <button type="submit" formaction="{{ url_for('payment.payment_index') }}" class="button_search">
        Buscar
    </button>
</form>
<section class="table-container">
    <table class="index-table box">
        <thead>
            <tr>
                <th class="name">Nro de Socio</th>
                <th class="name">Nombre</th>
                <th class="name">Apellido</th>
                <th class="name">Email</th>
                <th class="name">Acciones</th>
            </tr>
        </thead>
        <tbody>
            {% for user in users.items %}
            <tr>
                <th>{{ user.member_number }}</th>
                <th>{{ user.name }}</th>
                <th>{{ user.last_name }}</th>
                <th>{{ user.email}}</th>
                <th>
                    <button class="button_registarpago">
                        <a href="{{ url_for('payment.show', id=user.id )}}">Registrar Pago</a>
                    </button>
                </th>
            </tr>
            {% endfor %}
        </tbody>
    </table>
</section>


<!-- Setteamos el objeto users que tiene los usuarios y a su vez la 
    paginacion  para enviarselos al template paginacion.html 
    que usa por defecto la variable  pagination_items -->

{% set base_url = '/payment' %}

{% if request.args.get('search_field') %}
{% set search = '?search_field=' + request.args.get('search_field') %}
{% else %}
{% set search = "?search_field=" %}
{% endif %}


{% set pagination_items = users %} {% set url_redirect = base_url %}


{% include'layout/pagination.html' %}
{% endblock content %}

admin/src/web/templates/payment/report.html
{% extends 'layout/layout.html' %} {% block title %}Confirmación de pago{% endblock %}
{%block head %}
{{ super() }}
<link rel="stylesheet" href="{{ url_for('static', filename='forms/style.css') }}" />
{% endblock head %}
{%block content %}
<h1>Asociado: {{associate.name}} {{associate.last_name}}</h1>
<section class="sectionShow">
    <h1>Disciplinas :</h1>
    {% for d in todasDisciplinas %}
    <li>{{ d.name | capitalize }} </li>
    {% endfor %}

    <span class="labelShow"><strong>Mes: </strong>{{month}}</span>
    <span class="labelShow"><strong>Fecha: </strong>{{ datetime.now().strftime("%d/%m/%y") }}</span>
    <span class="labelShow"><strong>Total: </strong>{{costo_total}}</span>
</section>

<button class="button_registarpago">
    <a href="{{ url_for('payment.updatePayment',id=associate.id, id_pago=id_pago, total=costo_total )}}">Registrar
        Pago</a>
</button>
{% endblock content %}

admin/src/web/templates/payment/show.html
{% extends 'layout/layout.html' %} {% block title %}Pagos{% endblock %}
{%block content %} {{ super() }}
<h1>Registrar Pago<p>Asociado: {{user.name | capitalize }} {{user.last_name | capitalize }}</p>
    <p>Fecha: {{ datetime.now().strftime("%d/%m/%y") }}</p>
</h1>
{% if pending %}
<main class="section_table_and_disciplines">
    <div class="info_container">
        <p class="text_discipline">Disciplinas que realiza</p>
        {% if disciplines %}
            {% for d in disciplines %}
                <li>{{ d.name | capitalize }} </li>
            {% endfor %}
        {% else %}
        <p>-No hay disciclinas</p>
        {% endif %}
        <h2 class="text_pago">Total a pagar: ${{ total }} </h2>
    </div>
    <table class="index-table box">
        <thead>
            <tr>
                <th class="name">Mes</th>
                <th class="name">Abonar</th>
            </tr>
        </thead>
        <tbody>
            {% for payment in pending %}
            <tr>
                <th>{{ payment.mes.value }}</th>

                {% if payment.state.value == 'Pagado' %}
                <th>
                    <button class="button_registarpago">
                        <a href="#">
                            Pagado</a>
                    </button>
                    <button class="button_registarpago">
                        <a href="{{ url_for('payment.generate_voucher', id=user.id , id_pago=payment.id )}}">
                            Emitir Compronte</a>
                    </button>
                </th>
                    
                {% else %}
                     <th>
                    <button class="button_registarpago">
                        <a href="{{ url_for('payment.result', id=user.id , id_pago=payment.id )}}">Registrar
                            Pago</a>
                    </button>
                </th>
                {% endif %}

            </tr>
            {% endfor %}
        </tbody>
    </table>
</main>
{% else %}
<section class="containernotresult">
    <img img class="notresultimg" src="{{ url_for('static', filename='images/feedback-animate.svg') }}" />
    <span class="notresultext">No hay cuotas pendientes de pago</span>
</section>
{% endif %}
{% endblock content %}