admin/src/web/controllers/discipline.py
from flask import Blueprint
from flask import render_template
from flask import request
from flask import flash
from flask import url_for
from flask import redirect
from src.core import config
from src.core import disciplines
from src.web.helpers.permission import permisson_required
from src.web.utils.validations import CampoVAcio, isInteger

discipline_blueprint = Blueprint("disciplines", __name__, url_prefix="/disciplines")


@discipline_blueprint.get("/")
@discipline_blueprint.get("/<int:page_num>")
@permisson_required("discipline_index")
def discipline_index(page_num=1):
    """List all disciplines paginated"""
    paginated_disciplines = disciplines.list_disciplines(page_num=page_num, per_page=config.get_per_page())
    return render_template("disciplines/disciplines_list.html", disciplines=paginated_disciplines)


@discipline_blueprint.route("/create", methods=("GET", "POST"))
@permisson_required("discipline_new")
def create():
    if (
        request.method == "POST"
        and CampoVAcio(
            request.form.get("name"),
            request.form.get("category"),
            request.form.get("nameInstructors"),
            request.form.get("daysAndHours"),
            request.form.get("monthlyCost"),
        )
        and isInteger(request.form.get("monthlyCost"))
    ):
        name = request.form.get("name")
        category = request.form.get("category")
        nameInstructors = request.form.get("nameInstructors")
        daysAndHours = request.form.get("daysAndHours")
        monthlyCost = request.form.get("monthlyCost")
        disciplines.create_discipline(
            name=name,
            category=category,
            nameInstructors=nameInstructors,
            daysAndHours=daysAndHours,
            monthlyCost=monthlyCost,
        )
        flash("Disciplina creada correctamente", "success")
        return redirect((url_for("disciplines.discipline_index")))
    else:
        return render_template("disciplines/create.html")


@discipline_blueprint.route("/delete/<id>")
@permisson_required("discipline_destroy")
def delete(id):
    if disciplines.IsErasable(id):
        disciplines.delete_discipline(id=id)
        flash("Disciplina Eliminada Correctamente", "success")
        return redirect((url_for("disciplines.discipline_index")))
    else:
        flash(
            "No se puede eliminar la disciplina ya que tiene asociados inscriptos",
            "error",
        )
        return redirect((url_for("disciplines.discipline_index")))


@discipline_blueprint.route("/update/<id>", methods=["POST", "GET"])
@permisson_required("discipline_update")
def update(id):
    if (
        request.method == "POST"
        and CampoVAcio(
            request.form.get("name"),
            request.form.get("category"),
            request.form.get("nameInstructors"),
            request.form.get("daysAndHours"),
            request.form.get("monthlyCost"),
        )
        and isInteger(request.form.get("monthlyCost"))
    ):
        name = request.form["name"]
        category = request.form["category"]
        nameInstructors = request.form["nameInstructors"]
        daysAndHours = request.form["daysAndHours"]
        monthlyCost = request.form["monthlyCost"]
        disciplines.update_discipline(
            id=id,
            name=name,
            category=category,
            nameInstructors=nameInstructors,
            daysAndHours=daysAndHours,
            monthlyCost=monthlyCost,
        )
        flash("Disciplina editada correctamente", "success")
        return redirect((url_for("disciplines.discipline_index")))

    discipline = disciplines.get_discipline(id=id)
    return render_template("disciplines/update.html", discipline=discipline)


@discipline_blueprint.route("/show/<id>")
@permisson_required("discipline_show")
def show(id):
    discipline = disciplines.get_discipline(id=id)
    return render_template("disciplines/show.html", discipline=discipline)

@discipline_blueprint.route("/setStatus/<id>/<desactivado>")
def setStatus(id, desactivado):
    if not disciplines.IsErasable(id):
        flash("No se puede desactivar la disciplina ya que tiene asociados inscriptos", "error")
        return redirect((url_for("disciplines.discipline_index")))
    else:
        disciplines.setStatus(id=id)
        if (desactivado == '1'):
            flash("Disciplina desactivada correctamente", "success")
        else:
            flash("Disciplina activada correctamente", "success")
        return redirect((url_for("disciplines.discipline_index")))

admin/src/web/controllers/inscription.py
from flask import Blueprint
from flask import render_template
from flask import request
from flask import flash
from flask import url_for
from flask import redirect
from src.core import associates
from src.core import disciplines
from src.core import config
from src.core import payment
import datetime
from src.web.helpers.permission import permisson_required

inscription_blueprint = Blueprint("inscription", __name__, url_prefix="/inscription")


@inscription_blueprint.get("/")
@inscription_blueprint.get("<int:id>")
@inscription_blueprint.get("<int:page_num>/<int:id>")
@permisson_required("inscription_index")
def inscription(page_num=1, id=1):

    if not disciplines.isActive(id):
        flash("La disciplina no esta activa", "error")
        return redirect((url_for("disciplines.discipline_index")))
    search = request.args.get("search_field")

    paginated_associates = associates.list_associateActiveAndInactive(
        page_num=page_num,
        per_page=config.get_per_page(),
        search=search,
        nroSocio=False,
    )
    return render_template(
        "disciplines/inscriptions.html",
        associates=paginated_associates,
        idDisciplina=id,
    )


@inscription_blueprint.route("/doInscription/<id>/<idDisciplina>")
@permisson_required("inscription_create")
def doInscription(id, idDisciplina):
    inscription = disciplines.find_inscription_by_associate_and_discipline(
        idAssociate=id, idDiscipline=idDisciplina
    )
    if not inscription:
        # verificar si el socio está al dia con las cuotas
        if payment.esMoroso(id):
            flash("Error! el asociado es moroso", "error")
            # poner asociado en defaulter
            associates.setDefaulter(id)
            return redirect((url_for("inscription.inscription", id=idDisciplina)))
        else:
            associates.setNotDefaulter(id)
        if not associates.is_active(id):
            flash("El asociado no es activo", "error")
            return redirect((url_for("disciplines.discipline_index")))
        disciplines.createInscription(idAsociado=id, idDisciplina=idDisciplina)
        flash("Inscripcion realizada", "success")
    else:
        flash("El asociado ya se encuentra inscripto a la disciplina", "error")
    return redirect((url_for("disciplines.discipline_index")))


@inscription_blueprint.post("/search/<id>")
def search(id):
    params = request.form
    search = params["search_field"]

    paginated_associates = associates.list_associateActiveAndInactive(
        page_num=1,
        per_page=config.get_per_page(),
        search=search,
        nroSocio=False,
    )
    return render_template(
        "disciplines/inscriptions.html",
        associates=paginated_associates,
        idDisciplina=id,
    )

admin/src/web/templates/disciplines/create.html
{% extends 'layout/layout.html' %} {% block title %}Usuarios{% endblock %} 
{% block head %} 
    {{ super() }}
    <link rel="stylesheet" href="{{ url_for('static', filename='forms/style.css') }}" />
{% endblock head%}  
{%block content %} {{ super() }}
<h1 class="h1center">Agregar disciplina</h1>
<div class="form_container">
  <form action="{{ url_for('disciplines.create') }}" method="post">
    <label class="label" for="name">Nombre</label>
    <input class="input_text" type="text" id="name" name="name" required/>

    <label class="label" for="name">Categoria</label>
    <input class="input_text" type="text" id="cateogry" name="category" required/>

    <label class="label" for="name">Nombre y apellido instructores</label>
    <input class="input_text" type="text" id="nameInstructors" name="nameInstructors" required/>

    <label class="label" for="name">Dias y horarios</label>
    <input class="input_text" type="text" id="daysAndHours" name="daysAndHours" required/>

    <label class="label" for="name">Costo mensual</label>
    <input class="input_text" type="number" id="monthlyCost" name="monthlyCost" required/>

    <button type="submit" id="submit" class="button_add mt-3">Guardar</button>
  </form>
</div>
{% endblock content %}

admin/src/web/templates/disciplines/disciplines_list.html
{% extends 'layout/layout.html' %} {% block title %}Disciplinas{% endblock %}
{% block head %} {{super()}} {% endblock %}
{%block content %} {{ super() }}
{% if has_permission("discipline_new") %}
  <button class="button_add mt-3">
    <a href="{{ url_for('disciplines.create') }}">Nueva disciplina</a>
  </button>
{% endif %}
<h1>Listado de disciplinas</h1>
<section class="table-container">
  <table class="index-table box">
    <thead>
      <tr>
        <th class="name">Nombre</th>
        <th class="name">Categoria</th>
        <th class="name">Nombre insctructores</th>
        <th class="name">Dias y horarios</th>
        <th class="name">Cuota mensual</th>
        <th class="name">Acciones</th>
      </tr>
    </thead>
    <tbody>
      {% for discipline in disciplines.items %}
      <tr>
        <th>{{ discipline.name }}</th>
        <th>{{ discipline.category }}</th>
        <th>{{ discipline.nameInstructors}}</th>
        <th>{{ discipline.daysAndHours }}</th>
        <th>{{ discipline.monthlyCost}}</th>
        <th>
          <div>
              {% if has_permission("discipline_new") %}
                <a href="{{ url_for('disciplines.show', id=discipline.id )}}"><img class="icon" alt="Mas informacion" title="Mas informacion" src="{{ url_for('static', filename='images/discipline.svg') }}"/></a>
              {% endif %}
              {% if has_permission("discipline_update") %}
                <a href="{{ url_for('disciplines.update', id=discipline.id )}}"><img class="icon" alt="editar" title="Editar" src="{{ url_for('static', filename='images/edit.svg') }}"/></a>
              {% endif %}
              {% if has_permission("discipline_destroy") %}
                <a href="{{ url_for('disciplines.delete', id=discipline.id )}}" class="deleteconfirm"><img class="icon" alt="Eliminar" title="Eliminar" src="{{ url_for('static', filename='images/delete.svg') }}"/></a>
              {% endif %}
              {% if has_permission("discipline_new") %}
                <a href="{{ url_for('inscription.inscription', id=discipline.id )}}"><img class="icon" alt="Realizar Inscripcion" title="Realizar Inscripcion" src="{{ url_for('static', filename='images/add.svg') }}"/></a>
              {% endif %}
              {%if  discipline.active == True %}
              <a href="{{ url_for('disciplines.setStatus', id=discipline.id, desactivado=1) }}" class="activconfirm"><img class="icon" alt="Bloquear" title="Bloquear" src="{{ url_for('static', filename='images/on.svg') }}"/></a>
              {% else %}
              <a href="{{ url_for('disciplines.setStatus', id=discipline.id, desactivado=0) }}" class="bloqueoconfirm"><img class="icon" alt="Activar" title="Activar" src="{{ url_for('static', filename='images/off.svg') }}"/></a>
              {% endif %}
          </div>
        </th>
      </tr>
      {% endfor %}
    </tbody>
  </table>
</section>

<!-- Setteamos el objeto users que tiene los usuarios y a su vez la 
paginacion  para enviarselos al template paginacion.html 
que usa por defecto la variable  pagination_items -->
{% set pagination_items = disciplines %} 
{% set url_redirect = '/disciplines' %} 
{% include'layout/pagination.html' %} 
{% endblock content %}

admin/src/web/templates/disciplines/inscriptions.html
{% extends 'layout/layout.html' %} 
{% block title %}Asociados{% endblock %} 
{% block content %}
{{ super() }}

<h1>Listado de Asociados</h1>
{% if associates.items %}


<form class="filter_user" action="" method="POST">

  <input name="search_field" type="search" class="search-field" placeholder="buscar apellido" />

  <button type="submit" formaction="{{ url_for('inscription.search', id=idDisciplina) }}" class="button_search">
      Buscar
  </button>

</form>

<table class="index-table box">
  <thead>
    <tr>
      <th class="name">Nombre</th>
      <th class="name">Apellido</th>
      <th class="name">Email</th>
      <th class="name">Dni</th>
      <th class="name">Direccion</th>
      <th class="name">Acciones</th>
    </tr>
  </thead>
  <tbody>
    {% for associate in associates.items %}
    <tr>
      <th>{{ associate.name}}</th>
      <th>{{ associate.last_name}}</th>
      <th>{{ associate.email}}</th>
      <th>{{ associate.dni}}</th>
      <th>{{ associate.address}}</th>
      <th>
        {% if find_inscription_by_associate_and_discipline(associate.id,idDisciplina) %}
          <p>Asociado ya inscripto</p>
        {% else %}
         <a class="inscripcion" href="{{ url_for('inscription.doInscription', id=associate.id , idDisciplina=idDisciplina) }}">Inscribir a disciplina</a>
        {% endif %}
      </th>
    </tr>
    {% endfor %}
  </tbody>
</table>
{% else %}
<section class="containernotresult">
  <img img class="notresultimg" src="{{ url_for('static', filename='images/feedback-animate.svg') }}" />
  <span class="notresultext">No se encontraron resultados</span>
</section>
{% endif %}
<!-- Setteamos el objeto users que tiene los usuarios y a su vez la 
paginacion  para enviarselos al template paginacion.html 
que usa por defecto la variable  pagination_items -->
{% set pagination_items = associates %} 
{% set url_redirect = '/inscription' %}
{% set id_disciplina = idDisciplina %}
{% include'layout/pagination.html' %}


{% endblock content %}

admin/src/web/templates/disciplines/show.html
{% extends 'layout/layout.html' %} {% block title %}Disciplinas{% endblock %} 
{%block head %}
{{ super() }}
<link rel="stylesheet" href="{{ url_for('static', filename='forms/style.css') }}"/>
{% endblock head %} 
{%block content %}
<h1>Disciplina: {{discipline.name}}</h1>
<section class="sectionShow">
  <span class="labelShow"><strong>Nombre:</strong>     {{discipline.name}}</span>
  <span class="labelShow"><strong>Categoria:</strong> {{discipline.category}}</span>
  <span class="labelShow"><strong>Nombre Instructores:</strong> {{discipline.nameInstructors}}</span>
  <span class="labelShow"><strong>Dias y horarios:</strong> {{discipline.daysAndHours}}</span>
  <span class="labelShow"><strong>Cuota Mensual:</strong> ${{discipline.monthlyCost}}</span>
</section>
{% endblock content %}

admin/src/web/templates/disciplines/update.html
{% extends 'layout/layout.html' %} {% block title %}Disciplinas{% endblock %} 
{%block head %} 
{{ super() }}
<link rel="stylesheet" href="{{ url_for('static', filename='forms/style.css') }}" />
{% endblock head%} 
{%block content %}
{{ super () }}
<h1 class="h1center">Actualizar Disciplina</h1>
<div class="form_container">
  <form action="/disciplines/update/{{discipline.id}}" method="POST">
    <label class="label" for="name">Nombre*</label>
    <input class="input_text" type="text" id="name" name="name" value="{{discipline.name}}" required/>

    <label class="label" for="name">Categoria*</label>
    <input class="input_text" type="text" id="category" name="category" value="{{discipline.category}}" required/>

    <label class="label" for="name">Nombre instructores*</label>
    <input class="input_text" type="text" id="nameInstructors" name="nameInstructors" value="{{discipline.nameInstructors}}" required/>

    <label class="label" for="name">Dias y Horarios*</label>
    <input class="input_text" type="text" id="daysAndHours" name="daysAndHours" value="{{discipline.daysAndHours}}" required/>

    <label class="label" for="name">Cuota Mensual*</label>
    <input class="input_text" type="number" id="monthlyCost" name="monthlyCost" value="{{discipline.monthlyCost}}" required/>

    <button type="submit" id="submit" class="button_add mt-3">Actualizar</button>
  </form>
</div>
{% endblock content %}