admin/src/web/controllers/user.py
from operator import or_
from flask import Blueprint
from flask import render_template
from flask import request
from flask import flash
from flask import url_for
from flask import redirect
from src.core import auth
from src.core.permissions.role import Role
from src.web.utils.validations import CampoVAcio, validationMailAndPass,validationEmail
from src.core import config
from src.web.helpers.permission import permisson_required

users_blueprint = Blueprint("users", __name__, url_prefix="/users")


@users_blueprint.get("/")
@users_blueprint.get("/<int:page_num>")
@users_blueprint.get("<int:page_num>/<search>/<active>/")
@permisson_required("user_index")
def user_index(page_num=1):
    """Shows the user list view. It can use search fiters from get request"""

    search = request.args.get("search_field")
    active = request.args.get("active_filter")

    paginated_users = auth.list_users(page_num=page_num, per_page=config.get_per_page(), search=search, active=active)
    return render_template("users/users_list.html", users=paginated_users)


@users_blueprint.route("/create", methods=("GET", "POST"))
@permisson_required("user_new")
def create():
    """This function allows to create a new user and stores it the database.
    It also validate data"""
    if request.method == "POST":
        user_name = request.form.get("user_name")
        name = request.form.get("name")
        last_name = request.form.get("last_name")
        email = request.form.get("email")
        password = request.form.get("password")
        if CampoVAcio(name,last_name,email,user_name,password) and validationMailAndPass(email, password):
            rolesSelected=[]
            for rolId in request.form.getlist('rol'):
                unRol = Role.query.filter_by(id=rolId).first()
                rolesSelected.append(unRol)
            if not rolesSelected:
                flash("No se puede crear un usuario sin rol", "error")
                return redirect(url_for("users.create"))
            if (auth.usWithUserEmail(email)):
                flash("el email ingresado está ocupado", "error")
                return redirect(url_for("users.create"))
            if (auth.usWithUsername(user_name)):
                flash("el nombre de usuario ingresado está ocupado", "error")
                return redirect(url_for("users.create"))

            user = auth.create_user(email=email, password=password, name=name, last_name=last_name, user_name=user_name)
            auth.assigned_roles(user=user,rolesSelected=rolesSelected)
            flash("Usuario Creado Correctamente", "success")
            return redirect((url_for("users.user_index")))  

    return render_template("users/create.html")

@users_blueprint.route("/delete/<id>")
@permisson_required("user_delete")
def delete(id):
    auth.delete_user(id=id)
    flash("Usuario Eliminado Correctamente", "success")
    return redirect((url_for("users.user_index")))


@users_blueprint.route("/update/<id>", methods=["POST", "GET"])
@permisson_required("user_update")
def update(id):
    """Allows the update of an specific user"""
    if request.method == "POST":
        user_name = request.form.get("user_name")
        name = request.form.get("name")
        last_name = request.form.get("last_name")
        email = request.form.get("email")
        if CampoVAcio(name,last_name,email) and validationEmail(email):
            rolesSelected=[]
            for rolId in request.form.getlist('rol'):
                unRol = Role.query.filter_by(id=rolId).first()
                rolesSelected.append(unRol)
            if not rolesSelected:
                flash("No se puede elimiar todos los roles de un usuario", "error")
                return redirect(url_for("users.update",id=id))
            user_edit = auth.get_user(id)
            if (auth.usWithUsername(user_name) and auth.usWithUsername(user_name).id != user_edit.id):
                flash("el nombre de usuario ingresado está ocupado", "error")
                return redirect(url_for("users.update",id=id))
            
            if (auth.usWithUserEmail(email) and auth.usWithUserEmail(email).id != user_edit.id):
                flash("el email ingresado está ocupado", "error")
                return redirect(url_for("users.update", id=id))

            user = auth.update_user(id=id, email=email,user_name=user_name,name=name,last_name=last_name)
            for rol in rolesSelected:
                print(rol.id)
            auth.update_roles(user=user,rolesSelected=rolesSelected)
            flash("Usuario Modificado Correctamente", "success")
            return redirect((url_for("users.user_index")))

    user = auth.get_user(id=id)
    roles = Role.query.filter(or_(Role.nombre == 'admin', Role.nombre == 'operator'))
    return render_template("users/update.html", user=user, roles=roles)

@users_blueprint.route("/show/<id>")
@permisson_required("user_show")
def show(id):
    """Show user information card template"""
    user = auth.get_user(id=id)
    return render_template("users/show.html", user=user)

@users_blueprint.route("/setStatus/<id>/<desactivado>")
@permisson_required("user_activ")
def setStatus(id, desactivado):
    """Set user status (active/blocked)"""
    if auth.NoEsAdmin(id):
        auth.setStatus(id=id)
        if (desactivado == '1'):
            flash("Usuario Bloqueado Correctamente", "success")
        else:
            flash("Usuario Activado Correctamente", "success")
    else:
        flash("No se puede Bloquear un usuario Admin", "error")
    return redirect((url_for("users.user_index")))

admin/src/web/templates/users/create.html
{% extends 'layout/layout.html' %} {% block title %}Usuarios{% endblock %} 
{%block head %}
{{ super() }}
<link rel="stylesheet" href="{{ url_for('static', filename='forms/style.css') }}" />
{% endblock %} {%block content %} {{ super() }}
<h1 class="h1center">Agregar Usuario</h1>
<div class="form_container">
  <form action="{{ url_for('users.create') }}" method="post">
    <label class="label" for="name">Nombre*</label>
    <input class="input_text" type="text" id="name" name="name" required/>
    <label class="label" for="name">Apellido*</label>
    <input class="input_text" type="text" id="last_name" name="last_name" required/>
    <label class="label" for="name">Nombre de usuario*</label>
    <input class="input_text" type="text" id="user_name" name="user_name" required/>
    <label class="label" for="name">Email*</label>
    <input type="email" class="input_text" id="email" name="email" required/>
    <label class="label" for="name">Contraseña*</label>
    <input class="input_text" type="password" id="password" name="password" required/>
    <label class="label required" for="rol">Roles*</label>
    <input type="checkbox" name="rol" value="1" />Administrador
    <input type="checkbox" name="rol" value="2" />Operador
    <button type="submit" id="submit" class="button_add mt-3">Guardar</button>
  </form>
</div>
{% endblock content %}

admin/src/web/templates/users/show.html
{% extends 'layout/layout.html' %} {% block title %}Usuarios{% endblock %}
{%block head %}
{{ super() }}
<link rel="stylesheet" href="{{ url_for('static', filename='forms/style.css') }}" />
{% endblock head %}
{%block content %}

<div class="row justify-content-center mt-5">
  <section class="sectionShow">
    <h3>Datos del usuario: </h3>
    <span class="labelShow"><strong>Nombre: </strong>{{user.name}}</span>
    <span class="labelShow"><strong>Apellido: </strong>{{user.last_name}}</span>
    <span class="labelShow"><strong>Usuario: </strong>{{user.user_name}}</span>
    <span class="labelShow"><strong>Email: </strong>{{user.email}}</span>
  </section>
</div>

{% endblock content %}

admin/src/web/templates/users/update.html
{% extends 'layout/layout.html' %} {% block title %}Usuarios{% endblock %} {%
block head %}
{{super()}}
<link rel="stylesheet" href="{{ url_for('static', filename='forms/style.css') }}" />
{% endblock head%} {%block content %} {{ super() }}
<h1 class="h1center">Actualizar Usuario</h1>
<div class="form_container">
  <form action="/users/update/{{user.id}}" method="POST">
    <label class="label" for="name">Name</label>
    <input class="input_text" type="text" id="email" name="name" value="{{user.name}}" required/>

    <label class="label" for="name">Apellido</label>
    <input class="input_text" type="text" id="email" name="last_name" value="{{user.last_name}}" required/>

    <label class="label" for="name">Nombre De Ususario</label>
    <input class="input_text" type="text" id="email" name="user_name" value="{{user.user_name}}" required/>

    <label class="label" for="name">Email</label>
    <input class="input_text" type="email" id="email" name="email" value="{{user.email}}" required/>
    <label class="label" for="rol">Roles</label>
    {%for rol in roles%}
      {% if rol not in user.roles and has_permission("user_update") %}
          <input type="checkbox" name="rol" value="{{ rol.id }}">  
          <label>{{ rol.nombre }}</label>
      {% else %}
        {% if has_permission("user_update") %}
          <input type="checkbox" name="rol" value="{{ rol.id }}" checked>  
          <label>{{ rol.nombre }}</label>
            {% elif rol in user.roles %}
              <label>{{ rol.nombre }}</label>
            {% endif %}
      {% endif %}
    {%endfor%}
    <button type="submit" id="submit" class="button_add mt-3">Actualizar</button>
  </form>
</div>
{% endblock content %}

admin/src/web/templates/users/users_list.html
{% extends 'layout/layout.html' %} {% block title %}Usuarios{% endblock %}
{%block content %} 
{{ super() }}
<h1>Listado de usuarios</h1>
{% if has_permission("user_new") %}
<button class="button_add">
  <a href="{{ url_for('users.create') }}"><img alt="agregar" 
    src="{{ url_for('static', filename='images/Adduser.png') }}"/> Agregar</a>
</button>
{% endif %}
<form class="filter_user" action="" method="GET">
  <input name="search_field" type="search" class="search-field" placeholder="Buscar por email..." 
  {% if request.args.get('search_field') %} value="{{ request.args.get('search_field') }}" {% endif %}/>
  <select name="active_filter" class="search-field cp">
    <option value="True">Activo</option>
    <option value="False">Inactivo</option>
  </select>
  <button type="submit" formaction="{{ url_for('users.user_index') }}" class="button_search">
    Buscar
  </button>
</form>

{% if users.items %}
<section class="table-container">
  <table class="index-table box">
    <thead>
      <tr>
        <th class="name">Nombre</th>
        <th class="name">Apellido</th>
        <th class="name">Email</th>
        <th class="name">Acciones</th>
      </tr>
    </thead>
    <tbody>
      {% for user in users.items %}
      <tr>
        <th>{{ user.name }}</th>
        <th>{{ user.last_name }}</th>
        <th>{{ user.email}}</th>
        <th>
          {% if has_permission("user_show") %}
            <a href="{{ url_for('users.show', id=user.id )}}"><img class="icon" alt="Mas informacion" title="Mas informacion" src="{{ url_for('static', filename='images/info.svg') }}"/></a>
          {% endif %}
          {% if has_permission("user_update") %}
            <a href="{{ url_for('users.update', id=user.id )}}"><img class="icon" alt="editar" title="Editar" src="{{ url_for('static', filename='images/edit.svg') }}"/></a>
          {% endif %}
          {% if has_permission("user_destroy") %}
            <a href="{{ url_for('users.delete', id=user.id )}}" class="deleteconfirm"><img class="icon" alt="Eliminar" title="Eliminar" src="{{ url_for('static', filename='images/delete.svg') }}"/></a>
          {% endif %}
          {% if has_permission("user_activ") %}
            {%if  user.active == True %}
              <a href="{{ url_for('users.setStatus', id=user.id, desactivado=1) }}" class="activconfirm"><img class="icon" alt="Bloquear" title="Bloquear" src="{{ url_for('static', filename='images/on.svg') }}"/></a>
            {% else %}
              <a href="{{ url_for('users.setStatus', id=user.id, desactivado=0) }}" class="bloqueoconfirm"><img class="icon" alt="Activar" title="Activar" src="{{ url_for('static', filename='images/off.svg') }}"/></a>
            {% endif %}
          {% endif %}
        </th>
      </tr>
      {% endfor %}
    </tbody>
  </table>
</section>

  <!-- Setteamos el objeto users que tiene los usuarios y a su vez la 
  paginacion  para enviarselos al template paginacion.html 
  que usa por defecto la variable  pagination_items -->

  {% set base_url = '/users' %}

  {% if  request.args.get('search_field') %}
    {% set search = '?search_field=' + request.args.get('search_field') %}
  {% else %}
    {% set search = "?search_field=" %}
  {% endif %}
  
  
  {% if  request.args.get('active_filter') %}
    {% set active = '&active_filter=' + request.args.get('active_filter') %}
  {% else %}
    {% set active = "" %}
  {% endif %}
  
  {% set pagination_items = users %} {% set url_redirect = base_url %}
  {% include'layout/pagination.html' %}


{% else %}
  <section class="containernotresult">
    <img img class="notresultimg" src="{{ url_for('static', filename='images/feedback-animate.svg') }}" />
    <span class="notresultext">No se encontraron resultados</span>
  </section>
{% endif %}
{% endblock content %}