admin/src/web/controllers/associate.py
from core.payment import Payment
from src.core.associates.associate import DocumentType, Genero
from flask import Blueprint
from flask import render_template
from flask import request
from flask import flash
from flask import url_for
from flask import redirect
from src.core import associates
from src.web.utils.validations import CampoVAcio
from src.web.utils import exporters
from src.web.utils.validations import CampoVAcio, validationEmail, isInteger
from src.web.helpers.permission import permisson_required
from src.core import config
from base64 import b64encode

associates_blueprint = Blueprint("associates", __name__, url_prefix="/associates")


@associates_blueprint.get("/")
@associates_blueprint.get("/<int:page_num>")
@associates_blueprint.get("<int:page_num>/<search>/<active>/")
@permisson_required("member_index")
def associate_index(page_num=1):
    """Controller to display the associated index view"""

    search = request.args.get("search_field")
    active = request.args.get("active_filter")

    paginated_associates = associates.list_associate(
        page_num=page_num,
        per_page=config.get_per_page(),
        search=search,
        active=active,
        nroSocio=False,
    )
    return render_template(
        "associates/associates_list.html", associates=paginated_associates
    )



@associates_blueprint.route("/create", methods=("GET", "POST"))
@permisson_required("member_new")
def create():
    """Create an associated from a POST request"""
    if request.method == "POST":
        name = request.form.get("name")
        last_name = request.form.get("last_name")
        document_type = request.form.get("document_type")
        dni = request.form.get("dni")
        genero = request.form.get("genero")
        mobile_number = request.form.get("mobile_number")
        email = request.form.get("email")
        address = request.form.get("address")
        genero = request.form.get("genero")
        profile_picture = b64encode(request.files["profile_picture"].read())
        user_name = request.form.get("username")
        password = request.form.get("password")

        if CampoVAcio(
            name, last_name, document_type, dni, genero, address, user_name, password
        ):
            if not isInteger(request.form.get("dni")):
                flash("el dni no es valido", "error")
                return redirect(url_for("associates.create"))
            if not request.form.get("email") == "" and not validationEmail(
                request.form.get("email")
            ):
                return redirect(url_for("associates.create"))
            if not request.form.get("email") == "" and associates.usWithUserEmail(
                email
            ):
                flash("el email ingresado está ocupado", "error")
                return redirect(url_for("associates.create"))
            associate = associates.create_user(
                name=name,
                last_name=last_name,
                document_type=document_type,
                dni=dni,
                genero=genero,
                mobile_number=mobile_number,
                email=email,
                address=address,
                profile_picture=profile_picture,
                user_name=user_name,
                password=password,
            )
            associates.generar_pagos(id=associate.id)
            flash("Asociado Creado Correctamente", "success")
            return redirect((url_for("associates.associate_index")))

    document_type = DocumentType

    genero = Genero

    return render_template(
        "associates/create.html", document_type=document_type, genero=genero
    )


@associates_blueprint.route("/update/<id>", methods=["POST", "GET"])
@permisson_required("member_update")
def update(id):
    """Update an associated from a POST request"""
    if request.method == "POST":
        email = request.form.get("email")
        name = request.form.get("name")
        last_name = request.form.get("last_name")
        document_type = request.form.get("document_type")
        dni = request.form.get("dni")
        mobile_number = request.form.get("mobile_number")
        address = request.form.get("address")
        genero = request.form.get("genero")
        if CampoVAcio(name, last_name, document_type, dni, genero, address):
            user_edit = associates.get_associate(id)
            if not isInteger(request.form.get("dni")):
                flash("el dni no es valido", "error")
                return redirect(url_for("associates.update", id=id))
            if not request.form.get("email") == "" and not validationEmail(
                request.form.get("email")
            ):
                return redirect(url_for("associates.update", id=id))
            if (
                associates.usWithUserDni(dni)
                and associates.usWithUserDni(dni).id != user_edit.id
            ):
                flash("el dni ingresado ya existe", "error")
                return redirect(url_for("associates.update", id=id))
            associates.update_associate(
                id=id,
                email=email,
                name=name,
                last_name=last_name,
                document_type=document_type,
                dni=dni,
                mobile_number=mobile_number,
                address=address,
                genero=genero,
            )

            if request.files["profile_picture"]:
                profile_picture = b64encode(request.files["profile_picture"].read())
                associates.update_associate(id=id, profile_picture=profile_picture)

            flash("Asociado Modificado Correctamente", "success")
            return redirect((url_for("associates.associate_index")))

    associate = associates.get_associate(id=id)
    document_type = DocumentType
    genero = Genero
    return render_template(
        "associates/update.html",
        associate=associate,
        document_type=document_type,
        genero=genero,
    )


@associates_blueprint.route("/show/<id>")
@permisson_required("member_show")
def show(id):
    """Show personal information from an associated, returns a template"""
    associate = associates.get_associate(id=id)
    defaulter = associates.esMoroso(associate.id)
    associate.defaulter = defaulter
    return render_template("associates/show.html", associate=associate)


@associates_blueprint.route("/delete/<id>")
@permisson_required("member_destroy")
def delete(id):
    associates.delete_user(id=id)
    flash("Asociado Desactivado Correctamente", "success")
    return redirect((url_for("associates.associate_index")))


@associates_blueprint.route("/activate/<id>")
@permisson_required("member_destroy")
def activate(id):
    associates.activate(id=id)
    flash("Asociado Activado Correctamente", "success")
    return redirect((url_for("associates.associate_index")))


@associates_blueprint.get("/export/csv")
def call_csv_exporter():
    """Call to the util csv exporter. Uses search filters from get url"""
    search_filter = request.args.get("search_field")
    active_filter = request.args.get("active_filter")
    return call_some_exporter("csv", search_filter, active_filter)


@associates_blueprint.get("/export/pdf")
def call_pdf_exporter():
    """Call to the util pdf exporter. Uses search filters from get url"""
    search_filter = request.args.get("search_field")
    active_filter = request.args.get("active_filter")
    return call_some_exporter("pdf", search_filter, active_filter)


@associates_blueprint.get("/export/pdf/generate-license")
def generate_pdf_license():
    """Generates a PDF File for the associated license"""
    doc_type = request.args.get("doc_type")
    id_assoc = request.args.get("id_assoc")
    qr_url = request.args.get("qr_url_pdf")
    associated = associates.get_associate(id_assoc)
    defaulter = associates.esMoroso(associated.id)
    associated.defaulter = defaulter
    return exporters.choose_exporter(associated, doc_type, qr_url)


def call_some_exporter(doc_type, search_filter, active_filter):
    records = associates.list_associate_filtered(search_filter, active_filter)
    print(doc_type)
    return exporters.choose_exporter(records, doc_type)

admin/src/web/templates/associates/associates_list.html
{% extends 'layout/layout.html' %}
{% block title %}Asociados{% endblock %}
{% block content %}
{{ super() }}
<h1>Listado de Asociados</h1>
{% if has_permission("member_new") %}
<button class="button_add">
  <a href="{{ url_for('associates.create') }}">
    <img alt="agregar" src="{{ url_for('static', filename='images/Adduser.png') }}" /> Agregar</a>
</button>
{% endif %}
<form class="filter_user" action="" method="GET">
  <input name="search_field" type="search" class="search-field" placeholder="Buscar por apellido..." {% if
    request.args.get('search_field') %} value="{{ request.args.get('search_field') }}" {% endif %} />

  <select name="active_filter" class="search-field cp">

    {% if request.args.get('active_filter') == 'True' %}
    <option value="True" selected>Activo</option>
    <option value="False">Inactivo</option>
    {% elif request.args.get('active_filter') == 'False'%}
    <option value="False" selected>Inactivo</option>
    <option value="True">Activo</option>
    {% else %}
    <option value="True">Activo</option>
    <option value="False">Inactivo</option>
    {% endif %}

  </select>
  <button type="submit" formaction="{{ url_for('associates.associate_index') }}" class="button_search">
    Buscar
  </button>
  {% if associates.items %}
  <button type="submit" formaction="{{ url_for('associates.call_csv_exporter') }}" class="button_exporter">
    <input name="doc_type" value="csv" hidden />
    <a>
      <img alt="agregar" src="{{ url_for('static', filename='images/export_csv.png') }}">
      Exportar CSV
    </a>
  </button>
  <button type="submit" formaction="{{ url_for('associates.call_pdf_exporter') }}" class="button_exporter">
    <input name="doc_type" value="pdf" hidden />
    <a>
      <img alt="agregar" src="{{ url_for('static', filename='images/pdf_export.png') }}">
      Exportar PDF
    </a>
  </button>
</form>
<section class="table-container">
  <table class="index-table box">
    <thead>
      <tr>
        <th class="name">Nombre</th>
        <th class="name">Apellido</th>
        <th class="name">Email</th>
        <th class="name">Dni</th>
        <th class="name">Direccion</th>
        <th class="name">Acciones</th>
      </tr>
    </thead>
    <tbody>
      {% for associate in associates.items %}
      {% if  (associate.active == True)  or (associate.active == False and (request.args.get('active_filter') == 'False') ) %}
      <tr>
        <th>{{ associate.name}}</th>
        <th>{{ associate.last_name}}</th>
        <th>{{ associate.email}}</th>
        <th>{{ associate.dni}}</th>
        <th>{{ associate.address}}</th>
        <th>
          {% if has_permission("member_show") %}
          <a href="{{ url_for('associates.show', id=associate.id )}}"><img class="icon" alt="Mas informacion"
              title="Mas informacion" src="{{ url_for('static', filename='images/info.svg') }}" /></a>
          {% endif %}
          {% if has_permission("member_update") %}
          <a href="{{ url_for('associates.update', id=associate.id )}}"><img class="icon" alt="editar" title="Editar"
              src="{{ url_for('static', filename='images/edit.svg') }}" /></a>
          {% endif %}
          {% if has_permission("member_destroy") %}
              {% if (associate.active == False) %}
              <a href="{{ url_for('associates.activate', id=associate.id )}}" class="deleteconfirm"><img class="icon" alt="Activar" title="Activar" src="{{ url_for('static', filename='images/off.svg') }}"/></a>
              {% else %}
                  <a href="{{ url_for('associates.delete', id=associate.id )}}" class="deleteconfirm"><img class="icon"
                  alt="Eliminar" title="Desactivar" src="{{ url_for('static', filename='images/on.svg') }}" /></a>
              {% endif %}
          {% endif %}
        </th>
      </tr>
      {% endif %}
      {% endfor %}
    </tbody>
  </table>
</section>
{% else %}
<section class="containernotresult">
  <img img class="notresultimg" src="{{ url_for('static', filename='images/feedback-animate.svg') }}" />
  <span class="notresultext">No se encontraron resultados</span>
</section>
{% endif %}
<!-- Setteamos el objeto users que tiene los usuarios y a su vez la 
paginacion  para enviarselos al template paginacion.html 
que usa por defecto la variable  pagination_items -->

{% set base_url = '/associates' %}

{% if request.args.get('search_field') %}
{% set search = '?search_field=' + request.args.get('search_field') %}
{% else %}
{% set search = "?search_field=" %}
{% endif %}


{% if request.args.get('active_filter') %}
{% set active = '&active_filter=' + request.args.get('active_filter') %}
{% else %}
{% set active = "" %}
{% endif %}

{% set pagination_items = associates %} {% set url_redirect = base_url %}
{% include'layout/pagination.html' %}

{% endblock content %}

admin/src/web/templates/associates/create.html
{% extends 'layout/layout.html' %}
{% block title %} Asociados {% endblock %}
{%block head %}
{{ super() }}
<link rel="stylesheet" href="{{ url_for('static', filename='forms/style.css') }}" />
{% endblock head%}
{%block content %}
{{ super() }}
<h1 class="h1center">Nuevo Asociado</h1>
<div class="form_container">
  <form action="{{ url_for('associates.create') }}" enctype="multipart/form-data" method="post">
    <label class="label" for="name">Nombre*</label>
    <input class="input_text" type="text" id="email" name="name" required/>
    <label class="label" for="name">Apellido*</label>
    <input class="input_text" type="text" id="email" name="last_name" required/>
    <label class="label" for="name">Tipo de documento*</label>
    <select id="document_type" name="document_type" class="input_select" required>
      {%for tipo in document_type %}
      <option value="{{tipo.name}}">{{tipo.value}}</option>
      {%endfor%}
    </select>
    <label class="label" for="name">Numero de Documento*</label>
    <input type="number" class="input_text" type="text" name="dni" required/>
    <label class="label" for="name">Género*</label>
    <select id="genero" name="genero" class="input_select" required>
      {%for gen in genero %}
      <option value="{{gen.name}}">{{gen.value}}</option>
      {%endfor%}
    </select>
    <label class="label" for="name">Direccion*</label>
    <input class="input_text" type="text" id="email" name="address" required/>
    <label class="label" for="name">Email</label>
    <input class="input_text" type="email" type="text" id="email" name="email"/>
    <label class="label" for="name">Nombre de Usuario*</label>
    <input class="input_text" type="text" id="email" name="username" required/>
    <label class="label" for="name">Contraseña*</label>
    <input class="input_text" type="password" id="email" name="password" required/>
    <label class="label" for="name">Teléfono</label>
    <input type="number" class="input_text" type="text" id="email" name="mobile_number"/>
    <br><label class="label" for="name">Foto de perfil</label>
    <input type="file" class="" name="profile_picture" accept="image/*"/>
    <button type="submit" id="submit" class="button_add mt-3">Guardar</button>
  </form>
</div>
{% endblock content %}

admin/src/web/templates/associates/export-license.html
<title>Carnet Digital</title>

<style>
    @import url('https://fonts.googleapis.com/css?family=Abel');

    html,
    body {
        
        font-family: Abel, Arial, Verdana, sans-serif;
    }

    .center {
        position: absolute;
        top: 25%;
        left: 0%;
    }

    .card {
        width: 450px;
        height: 260px;
        background-color: #fff;
        background: linear-gradient(#f8f8f8, #fff);
        box-shadow: 0 8px 16px -8px rgba(0, 0, 0, 0.4);
        border-radius: 6px;
        overflow: hidden;
        position: relative;
        margin: 5.5rem;
    }

    .card h1 {
        text-align: center;
    }

    .card .additional {
        position: absolute;
        width: 150px;
        height: 100%;
        background: linear-gradient(#dE685E, #EE786E);
        transition: width 0.4s;
        overflow: hidden;
        z-index: 2;
    }

    .card.green .additional {
        background: linear-gradient(#92bCa6, #A2CCB6);
    }


    .card:hover .additional {
        width: 100%;
        border-radius: 0 5px 5px 0;
    }

    .card .additional .user-card {
        width: 150px;
        height: 100%;
        position: relative;
        float: left;
    }

    .card .additional .user-card::after {
        content: "";
        display: block;
        position: absolute;
        top: 10%;
        right: -2px;
        height: 80%;
        border-left: 2px solid rgba(0, 0, 0, 0.025);
    }

    .card .additional .user-card .level,
    .card .additional .user-card .points {
        top: 15%;
        color: #fff;
        text-transform: uppercase;
        font-size: 0.75em;
        font-weight: bold;
        background: rgba(0, 0, 0, 0.15);
        padding: 0.125rem 0.75rem;
       
        white-space: nowrap;
    }

    .card .additional .user-card .points {
        top: 85%;
    }

    .card .additional .user-card svg {
        top: 50%;
    }

    .card .additional .more-info {
        width: 300px;
        float: left;
        position: absolute;
        left: 150px;
        height: 100%;
    }

    .card .additional .more-info h1 {
        color: #fff;
        margin-bottom: 0;
    }

    .card.green .additional .more-info h1 {
        color: #224C36;
    }

    .card .additional .coords {
        margin: 0 1rem;
        color: #fff;
        font-size: 1rem;
    }

    .card.green .additional .coords {
        color: #325C46;
    }

    .card .additional .coords span+span {
        float: right;
    }

    .card .additional .stats {
        font-size: 2rem;
        display: flex;
        position: absolute;
        bottom: 1rem;
        left: 1rem;
        right: 1rem;
        top: auto;
        color: #fff;
    }

    .card.green .additional .stats {
        color: #325C46;
    }

    .card .additional .stats>div {
        flex: 1;
        text-align: center;
    }

    .card .additional .stats i {
        display: block;
    }

    .card .additional .stats div.title {
        font-size: 0.75rem;
        font-weight: bold;
        text-transform: uppercase;
    }

    .card .additional .stats div.value {
        font-size: 1.5rem;
        font-weight: bold;
        line-height: 1.5rem;
    }

    .card .additional .stats div.value.infinity {
        font-size: 2.5rem;
    }

    .card .general {
        width: 300px;
        height: 100%;
        position: absolute;
        top: 0;
        right: 0;
        z-index: 1;
        box-sizing: border-box;
        padding: 1rem;
        padding-top: 0;
    }

    .card .general .more {
        position: absolute;
        bottom: 1rem;
        right: 1rem;
        font-size: 0.9em;
    }
</style>

    <div class="card green">
        <div class="additional">
            <div class="user-card">
                <div class="level center">
                    Club Deportivo Villa Elisa
                </div>
            </div>
        </div>
        <div class="general">
            <h1>{{associate.name}} {{associate.last_name}}</h1>
            <p>Nro. Socio: {{associate.member_number}}</p>
            <p>DNI: {{associate.dni}}</p>
            <p>Teléfono: {{associate.mobile_number}}</p>
            <p>Email: {{associate.email}}</p>
            <p>Fecha alta: {{associate.create_at.strftime('%d/%m/%Y')}}</p>
            <span class="more"> {% set QR = qrcode(qr_url, box_size=2) %}
                <img style="float: right;" src="{{ QR }}"></span>
        </div>
    </div>

admin/src/web/templates/associates/report.html
<link rel="stylesheet" href="{{ url_for('static', filename='report/css/report-pdf.css') }}" />
<title>Listado de Socios</title>
<img src="{{ url_for('static', filename='images/favicon.ico') }}">
<div class="titulo">
    <h2>Listado de Socios</h2>
</div>
<div class="table-wrapper">
    <table class="fl-table">
        <thead>
            <tr>
                <th>Apellido</th>
                <th>Nombre</th>
                <th>Email</th>
                <th>N°Socio</th>
                <th>DNI</th>
                <th>Dirección</th>
                <th>Teléfono</th>
                <th>Género</th>
            </tr>
        </thead>
        <tbody>
            {% for associate in associates %}
            <tr>
                <td>{{ associate.last_name}}</td>
                <td>{{ associate.name}}</td>
                <td>{{ associate.member_number}}</td>
                <td>{{ associate.dni}}</td>
                <td>{{ associate.email}}</td>
                <td>{{ associate.address}}</td>
                <td>{{ associate.mobile_number}}</td>
                <td>{{ associate.genero.value}}</td>
            </tr>
            {% endfor %}
        <tbody>
    </table>
</div>

admin/src/web/templates/associates/show.html
{% extends 'layout/layout.html' %} {% block title %}Carnet Digital{% endblock %}
{%block head %}
{{ super() }}
<link rel="stylesheet" href="{{ url_for('static', filename='report/css/show-associated.css') }}" />
{% endblock head %}
{%block content %}

<div class="d-flex justify-content-end">
  <form method="get">
    <button style="float: right" class="btn btn-danger m-2 text-dark" type="submit"
      formaction="{{ url_for('associates.generate_pdf_license') }}">
      <input name="doc_type" value="pdf-license" hidden />
      <input name="id_assoc" value="{{ associate.id }}" hidden />
      <input name="qr_url_pdf" value="{{ request.url }}" hidden />
      <a><img src="{{ url_for('static', filename='images/pdf_license.svg') }}" />Exportar</a>
    </button>
  </form>
</div>

<div class="page-content page-container">
  <div class="padding d-flex justify-content-center">
    <div class="row container d-flex justify-content-center">
      <div class="col-xl-6 col-md-12">
        <div class="card user-card-full">
          <div class="row m-l-0 m-r-0">
            <div class="col-sm-4 bg-c-lite-green user-profile">
              <div class="card-block text-center text-white">
                <div class="m-b-25">
                  <img src="" class="rounded-circle border border-dark border-1" id="img" width="90" height="90">
                  <script>
                    data = "{{ associate.profile_picture }}"
                    data = data.replace("b&#39;", "")
                    data = data.replace("&#39;", "")
                    document.getElementById("img").src = "data:image/png;base64," + data; // set src
                  </script>
                </div>
                <h6 class="f-w-600">Asociado</h6>
                <p>{{associate.name}} {{associate.last_name}}</p>
                <i class=" mdi mdi-square-edit-outline feather icon-edit m-t-10 f-16"></i>
              </div>
            </div>
            <div class="col-sm-8 div-card">
              <div class="card-block">
                <h6 class="m-b-20 p-b-5 b-b-default f-w-600">Carnet Digital</h6>
                <div class="row">
                  <div class="col-sm-6">
                    <p class="m-b-10 f-w-600">Email</p>
                    <h6 class="text-muted f-w-400">{{associate.email}}</h6>
                  </div>
                  <div class="col-sm-6">
                    <p class="m-b-10 f-w-600">Teléfono</p>
                    <h6 class="text-muted f-w-400">{{associate.mobile_number}}</h6>
                  </div>
                </div>
                <div class="row">
                  <div class="col-sm-6">
                    <p class="m-b-10 f-w-600">DNI</p>
                    <h6 class="text-muted f-w-400">{{associate.dni}}</h6>
                  </div>
                  <div class="col-sm-6">
                    <p class="m-b-10 f-w-600">N° Socio</p>
                    <h6 class="text-muted f-w-400">{{associate.member_number}}</h6>
                  </div>
                </div>
                <h6 class="m-b-20 m-t-40 p-b-5 b-b-default f-w-600"></h6>
                <div class="row">
                  <div class="col-sm-6">
                    <p class="m-b-10 f-w-600">Estado</p>
                    {% if  associate.defaulter == True %}
                        <h6 style="color: red;">Moroso</h6>
                    {% else %}
                        <h6 style="color: green;">Al día</h6>
                    {% endif %}
                    <p class="m-b-10 f-w-600">Fecha Alta</p>
                    <h6 class="text-muted f-w-400">{{associate.create_at.strftime('%d/%m/%Y')}}</h6>
                  </div>
          
                  <div class="col-sm-6 mt-3">
                    {% set QR = qrcode(request.url, box_size=3) %}
                    <img style="float: right;" src="{{ QR }}">
                  </div>
                </div>

              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>

{% endblock content %}

admin/src/web/templates/associates/update.html
{% extends 'layout/layout.html' %} {% block title %}Usuarios{% endblock %}
{%block head %}
{{ super() }}
<link rel="stylesheet" href="{{ url_for('static', filename='forms/style.css') }}" />
{% endblock head%}
{%block content %}
{{ super () }}
<h1 class="h1center">Actualizar Asociado</h1>
<div class="form_container">
  <form action="/associates/update/{{associate.id}}" enctype="multipart/form-data" method="post">
    <label class="label" for="name">Nombre*</label>
    <input class="input_text" type="text" value="{{associate.name}}" name="name" required />
    <label class="label" for="name">Apellido*</label>
    <input class="input_text" type="text" value="{{associate.last_name}}" id="email" name="last_name" required/>
    <label class="label" for="name">Tipo de documento*</label>
    <select id="document_type" name="document_type" class="input_select" required>
      {%for tipo in document_type %}
      <option value="{{tipo.name}}" {% if associate.document_type.name == tipo.name %}selected{% endif %}>{{tipo.value}}
      </option>
      {%endfor%}
    </select>
    <label class="label" for="name">Numero de Documento*</label>
    <input class="input_text" type="number" value="{{associate.dni}}" id="email" name="dni" required />
    <label class="label" for="name">Genero*</label>
    <select id="genero" name="genero" class="input_select" required>
      {%for gen in genero %}
      <option value="{{gen.name}}" {% if associate.genero.name == gen.name %}selected{% endif %}>{{gen.value}}</option>
      {%endfor%}
    </select>
    <label class="label" for="name">Direccion*</label>
    <input class="input_text" type="text" value="{{associate.address}}" id="email" name="address" required />
    <label class="label" for="name">Email</label>
    <input class="input_text" type="email" value="{{associate.email}}" id="email" name="email"/>
    <label class="label" for="name">Telefono</label>
    <input class="input_text" type="number" value="{{associate.mobile_number}}" id="email" name="mobile_number" />
    <br><label class="label" for="name">Foto de perfil</label>
    <input type="file" class="" name="profile_picture" accept="image/*" />
    <button type="submit" id="submit" class="button_add mt-3">Guardar</button>
  </form>
</div>
{% endblock content %}